### ISSUE TITLE
Messaging app through location

### ISSUE THREAD

**Issue by graffic** [bkkhack/hacknights#134]
The idea is to build a messaging app where you leave messages in a location instead of sending them to a person.

**Comment by ches** [comment]
What are you using to build it?

**Comment by graffic** [comment]
@ches Xcode and firebase for now

**Comment by NorakGithub** [comment]
I wanna join this.

**Comment by zshanhui** [comment]
Like leaving hidden notes for people to find?

**Comment by ches** [comment]
Back in the day before Swarm became a thing, Foursquare was better at letting you find places that were trending **right now**, which I really miss. It could help you find what spots are popular to go out if you were feeling social, or discover events if you had enough time to react to them, like all-day weekend festivals, etc. 

I don't know if that's related to what you're thinking about or if it's more like on the city level or something like that, or almost geocaching-esque like @adrienshen asked. I just shared because I miss that functionality 😄 

> Xcode and firebase for now

Does that mean Swift then? Somewhat related, you might find [this not-yet-broadcast event](http://www.meetup.com/bkkhack/events/233662159/) of interest.

**Comment by arafalov** [comment]
I think William Gibson's Pattern Recognition (or maybe Spook's country) had the concept of that. And, more IRL, there was the PokemonGo chat app that went viral and then went dead. http://www.theverge.com/2016/7/11/12153370/gochat-pokemon-go-chat-app-jonathan-zarra-interview

**Comment by Alimariemac** [comment]
Hello, I'm interested in joining this! But I'm fairly new to coding so I may not be able to help much but I'm interested!
