### ISSUE TITLE
Node Bot

### ISSUE THREAD

**Issue by jjmax75** [bkkhack/hacknights#94]
Look at how to create a Bot to send alerts when hard to find tickets become available on sites like Ticket Master or Seat Wave.
Just researching it now and playing around with some possibilities.
Need to pick an event and website to experiment on.

**Comment by murnax** [comment]
I'm interested learn create bot, I have some experiences with Node but don't know about Bot. Do you have any module you are testing on? So I'll check it out before joining you.

**Comment by jjmax75** [comment]
Hi, I've nothing setup yet, this is the very early stages of an idea we had and just going to explore it tonight.
You're more than welcome to join. We'll be coming at this from the perspective of building something generic that can be adapted for use on any site.
See you tonight :)

**Comment by ches** [comment]
@bighappyworld Don't know if you're coming this time but you might have some pointers for these folks?

**Comment by veerabs** [comment]
Hi, interested in this. Anyone arrived yet?

**Comment by jjmax75** [comment]
hey man, here on the banana table :)

**Comment by jjmax75** [comment]
line - jjmax75

**Comment by denvergj** [comment]
line - demba93

**Comment by graffic** [comment]
line - javiergonel

**Comment by jjmax75** [comment]
line -veera.bs

**Comment by h-nasu** [comment]
line - hiro.nasu

**Comment by jjmax75** [comment]
GitLab repo setup, just need to add Hiro
Line Group setup too

**Comment by bighappyworld** [comment]
Didn’t see the mention until too late. Was busy.

What was the result?

Little things:

Skype Bot: Very unstable. It works differently or doesn’t work on every
user platform… iPhone vs iPad vs OS X vs Skype Web vs Windows Phone… all
behave differently so I’d avoid this until it is more stable. It has http
endpoints but you also have to manually include the Skype modules as they
aren’t on npm.

Facebook Bot: This requires some weird setup but it is mostly a few
endpoints on a server that Facebook posts to. It becomes a little bit of a
pain to do local development because when you hook it up to a Facebook page
you can’t change the URL unless you delete the application and make a new
one. It also has a weird setup in that a bot is a “page” and all messages
to the page get forwarded to the bot. I used ngrok to make a tunnel for
development here.

Slack Bot: This is a web socket based bot so it is much easier for local
development. The node botkit by howdy.ai (these guys have Slack as an
investor) is easy to use and it can also be used for Facebook Bots. The
complexity comes in maintaining the connection and scaling issues, but
pretty sure that isn’t an issue for hack night.

There are some other platforms popping up, but these are the ones I’ve
implemented. I’d say Slack bots are your easiest to implement quickly, they
function the same as a normal Slack client.

On June 30, 2016 at 4:37:03 PM, Ches Martin (notifications@github.com)
wrote:

@bighappyworld https://github.com/bighappyworld Don't know if you're
coming this time but you might have some pointers for these folks?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
https://github.com/bkkhack/hacknights/issues/94#issuecomment-229610894,
or mute the thread
https://github.com/notifications/unsubscribe/AE1kzJBh39RtkoWgJjk10lxkbCLlPRDwks5qQ44-gaJpZM4JAK7k
.

**Comment by ches** [comment]
By the way you all can feel free to create a new room on Gitter under the bkkhack organization if you'd like, if you don't seem to have permission to do that let me know. Rooms don't have to be associated with GitHub repos.

The Gitter apps—web and mobile—leave a lot to be desired though, so I wouldn't blame you for using another alternative if more convenient…

**Comment by jjmax75** [comment]
Thanks guys.
@bighappyworld we resolved at the start to see if we could build a bot that would find a ticket for a flight on a specific date within a specific price range then, if found, the bot would purchase the ticket.
We picked the Air Asia site as the playground. No malicious intent or anything, it just didn't seem to have much in the way of security (captcha, etc...) so was low hanging fruit :)
I have to admit I was along for the ride for much of this :) Denver built the side of the app that uses a Get request to check if the ticket is available using Node. Hiro built the bit that uses Casper JS to simulate user interaction with the page to fulfill the order. We're working on building out the frontend and also integrating both parts of the Bot.
We're hoping to meetup again in a couple of weeks if you're interested in hacking on this with us.
